title: Geographic standards and identifiers
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: false
  include:
    - index.md
    - formats/*.md
    - identifiers/*.md
  exclude:
    - README.md

